### ISSUE TITLE
Fix the column border length issue

### ISSUE THREAD

**Issue by camerican** [camerican/NYCDA_SCC16_Jasmine#2]
The column border length does not match when the contents of the columns causes different heights of the containers...  to fix that, you could apply the following rule to the taller content area:

``` css
.col.two{
       /* your other css rules */
    position:relative;
}
.col.two:before{
    position: absolute;
    left: -10px;
    height: 100%;
    border-left: 1px dashed rgb(255, 30, 100);
    content: '';
}
```

By setting the .col.two selector to position:relative and using a pseudo selector .col.two:before as position:absolute, we can make a second 100% tall border next to the one that occurs as part of .col.two.

![screen shot 2016-08-08 at 12 31 08 pm](https://cloud.githubusercontent.com/assets/2566680/17487709/04f2acd0-5d64-11e6-9206-29b09da85cc9.png)
